### ISSUE TITLE
Add Coursera courses into lab docs

### ISSUE THREAD

**Issue by handwerkerd** [nimh-sfim/lab-docs#46]
Several of you have been taking Coursera courses. If you've found good courses for others to consider taking (either Coursera or elsewhere), comment here or add them directly to lab-docs (probably in the programming or data science sections). I'm not sure who has been actively using Coursera, but I'm tagging: @javiergcas @ryesaam & @IsabelF98

**Comment by Micahh222** [comment]
Machine Learning Foundations: A Case Study Approach by University of Washington (recommended to me by Javier)
>> explains basic machine learning concepts using GraphLab (must install Turicreate instead*)

https://www.coursera.org/programs/data-science-machine-learning-yskdy?currentTab=CATALOG
