### ISSUE TITLE
Make instructions for making a miniconda environment on biowulf

### ISSUE THREAD

**Issue by handwerkerd** [nimh-sfim/lab-docs#48]
Make sure to have both the instructions and an easy way to initialize it since conda cannot be the default python in a biowulf user account.

**Comment by handwerkerd** [comment]
I made a list of recommended & suggested libraries to install on redmine. I really thought I transferred it over here, but can't seem to find it. A space for those recommendations should be included.

**Comment by jbteves** [comment]
Closed by #54
